### ISSUE TITLE
Contribution - Modified Original Bip S WatchFace (Simpler and bigger graph)

### ISSUE THREAD

**Issue by D-MSol4** [twinko/xdrip-watchface-collection#10]
![photo_2023-11-23_18-33-01](https://github.com/twinko/xdrip-watchface-collection/assets/81837486/870e3a0a-eba1-4077-afc1-33b8ad6f00cc)
[Modified watchface Bip S.zip](https://github.com/twinko/xdrip-watchface-collection/files/13452604/Modified.watchface.Bip.S.zip)

**Comment by twinko** [comment]
@DMS4444 Hi thank you so much. Does this WF has AOD`?

**Comment by twinko** [comment]
Hi @DMS4444 thank you so much! Does your WF has AOD  (always on display)?
Btw its already published :)

**Comment by D-MSol4** [comment]
> Hi @DMS4444 thank you so much! Does your WF has AOD  (always on display)?
> Btw its already published :)

Yes it has!
![IMG_20231123_214455.jpg](https://github.com/twinko/xdrip-watchface-collection/assets/81837486/ea0dd960-def3-4552-9623-fb5bc3c8e869)

**Comment by twinko** [comment]
@DMS4444 sweet ill upload this picture as well and changhe the discribtion. Thank you again !
